workspace 'JALCommunityPage.xcworkspace'
project 'JALCommunityPage.xcodeproj'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def commpod
    pod 'MGJRouter'
end

target 'JALCommunityPage' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  project 'JALCommunityPage.xcodeproj'
  commpod
  # Pods for JALCommunityPage
  
end

target 'TestPage' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    project 'TestPage.xcodeproj'
    commpod
end
